version: "3.9"
services:
  gaia:
    container_name: gaia-production
    build: .
    ports:
      - '8080:80'
    expose:
      - '80'
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    container_name: mysql-production
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: pr4m
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      SERVICE_TAGS: prod
      SERVICE_NAME: mysql
    ports:
      - '3306:3306'
    command: --sql_mode="" --general-log=1 --general-log-file=/var/lib/mysql/mysql.log
    volumes:
     - ./db/Dump20221215.sql:/docker-entrypoint-initdb.d/Dump20221215.sql
     - mysql_db:/var/lib/mysql
    
volumes:
  mysql_db: